name: nougat
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=11.8
  - mkl=2023.1.0
  - pip=25.3
